#ifndef BLU2USB_DOMAIN_PROFILE_H
#define BLU2USB_DOMAIN_PROFILE_H

typedef enum {
    BLU2USB_MOUSE_SOURCE_LEFT = 0,
    BLU2USB_MOUSE_SOURCE_RIGHT,
    BLU2USB_MOUSE_SOURCE_MIDDLE,
    BLU2USB_MOUSE_SOURCE_FORWARD,
    BLU2USB_MOUSE_SOURCE_BACKWARD,
    BLU2USB_MOUSE_SOURCE_COUNT
} blu2usb_mouse_source_t;

typedef enum {
    BLU2USB_MOUSE_TARGET_LEFT = 0,
    BLU2USB_MOUSE_TARGET_RIGHT,
    BLU2USB_MOUSE_TARGET_MIDDLE,
    BLU2USB_MOUSE_TARGET_BACKWARD,
    BLU2USB_MOUSE_TARGET_FORWARD,
    BLU2USB_MOUSE_TARGET_ESCAPE,
    BLU2USB_MOUSE_TARGET_COUNT
} blu2usb_mouse_target_t;

typedef struct {
    blu2usb_mouse_target_t target[BLU2USB_MOUSE_SOURCE_COUNT];
} blu2usb_custom_template_t;

#endif
